version: '3'
services:
  account-service:
    image: account-service
    ports:
      - 8086:8086
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/retail_banking_sys
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TungShieda@15
  auth-ms:
    image: auth-ms
    ports:
      - 8084:8084
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/retail_banking_sys
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TungShieda@15
  customer-ms:
    image: customer-ms
    ports:
      - 8085:8085
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/retail_banking_sys
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TungShieda@15
  rules-service:
    image: rules-service
    ports:
      - 8090:8090
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/retail_banking_sys
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TungShieda@15
  transaction-ms:
    image: transaction-ms
    ports:
      - 8087:8087
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/retail_banking_sys
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TungShieda@15
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: TungShieda@15
      MYSQL_DATABASE: retail_banking_sys
    ports:
      - 3306:3306
